spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mariadb:10.6.4:///
  flyway:
    enabled: true
  jpa:
    properties:
      jakarta:
        persistence:
          schema-generation:
            database:
              action: validate

integration:
  party:
    url: http://localhost:${wiremock.server.port}/party
    oauth2:
      token-uri: http://localhost:${wiremock.server.port}/token
      client-id: someClientId
      client-secret: someClientSecret
