spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mariadb:10.6.4:////ittest
  flyway:
    enabled: false
  jpa:
    properties:
      jakarta:
        persistence:
          schema-generation:
            database:
              action: update

  security:
    oauth2:
      client:
        registration:
          messaging:
            client-id: someClientId
            client-secret: someClientSecret
          party:
            client-id: someClientId
            client-secret: someClientSecret
        provider:
          messaging:
            token-uri: http://localhost:${wiremock.server.port}/api-token
          party:
            token-uri: http://localhost:${wiremock.server.port}/api-token

integration:
  messaging:
    url: http://localhost:${wiremock.server.port}/api-messaging
  party:
    url: http://localhost:${wiremock.server.port}/api-party
  sftp:
    municipalityIds:
      2281:
        user: user
        password: pass
        remoteDir: "/upload/"
        allowUnknownKeys: false

errorreport:
  recipients:
    - receiver@noreply.com
  sender: sender@noreply.com