spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mariadb:10.6.4:////ittest
  flyway:
    enabled: true
  jpa:
    properties:
      jakarta:
        persistence:
          schema-generation:
            database:
              action: validate

  security:
    oauth2:
      client:
        registration:
          messaging:
            client-id: someClientId
            client-secret: someClientSecret
          party:
            client-id: someClientId
            client-secret: someClientSecret
        provider:
          messaging:
            token-uri: http://localhost:${wiremock.server.port}/token
          party:
            token-uri: http://localhost:${wiremock.server.port}/token

integration:
  messaging:
    url: http://localhost:${wiremock.server.port}/messaging
  party:
    url: http://localhost:${wiremock.server.port}/party
