spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mariadb:10.6.4:///
  jpa:
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          schema-generation:
            script:
              append: false
      jakarta:
        persistence:
          schema-generation:
            create-source: metadata
            database:
              action: update
            scripts:
              action: create
              create-target: target/database/generated-schema.sql

  security:
    oauth2:
      client:
        registration:
          messaging:
            client-id: messagingClientId
            client-secret: messagingClientSecret
          party:
            client-id: partyClientId
            client-secret: partyClientSecret
        provider:
          messaging:
            token-uri: http://token.url
          party:
            token-uri: http://token.url

integration:
  messaging:
    url: http://messaging.url
    connectTimeout: 12
    readTimeout: 23
  party:
    url: http://party.url
    connect-timeout: 11
    read-timeout: 22
