spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mariadb:10.6:///
  jpa:
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          schema-generation:
            script:
              append: false
      jakarta:
        persistence:
          schema-generation:
            create-source: metadata
            database:
              action: update
            scripts:
              action: create
              create-target: target/database/generated-schema.sql

  security:
    oauth2:
      client:
        registration:
          messaging:
            client-id: messagingClientId
            client-secret: messagingClientSecret
          party:
            client-id: partyClientId
            client-secret: partyClientSecret
        provider:
          messaging:
            token-uri: http://token.url
          party:
            token-uri: http://token.url

integration:
  messaging:
    url: http://messaging.url
    connectTimeout: 12
    readTimeout: 23
  party:
    url: http://party.url
    connect-timeout: 11
    read-timeout: 22
  sftp:
    municipalityIds:
      2281:
        user: user
        password: pass
        remoteDir: "/upload/"
        allowUnknownKeys: false
      2282:
        user: user2
        password: pass2
        remoteDir: "/upload2/"
        allowUnknownKeys: false

errorreport:
  creation-error-mail-template:
    subject: creationErrorSubject
    html-prefix: creationErrorHtmlPrefix
    body-prefix: creationErrorBodyPrefix
    list-prefix: creationErrorListPrefix
    list-item: creationErrorListItem
    list-suffix: creationErrorListSuffix
    body-suffix: creationErrorBodySuffix
    html-suffix: creationErrorHtmlSuffix
  transfer-error-mail-template:
    subject: transferErrorSubject
    html-prefix: transferErrorHtmlPrefix
    body-prefix: transferErrorBodyPrefix
    list-prefix: transferErrorListPrefix
    list-item: transferErrorListItem
    list-suffix: transferErrorListSuffix
    body-suffix: transferErrorBodySuffix
    html-suffix: transferErrorHtmlSuffix
  recipients:
    - recipient.1
    - recipient.2
  sender: sender
