logging:
  level:
    root: INFO
openapi:
  name: ${spring.application.name}
  title: ${spring.application.name}
  version: '@project.version@'
spring:
  application:
    name: api-billing-preprocessor
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
  flyway:
    enabled: false
  jpa:
    properties:
      jakarta:
        persistence:
          schema-generation:
            database:
              action: none
  security:
    oauth2:
      client:
        registration:
          messaging:
            authorization-grant-type: client_credentials
            provider: messaging
          party:
            authorization-grant-type: client_credentials
            provider: party
invoicecreator:
  record-terminator: \n
mdc:
  municipalityId:
    enabled: true
scheduler:
  createfiles:
    # At 0000 every day
    cron: 0 0 0 * * *
  transferfiles:
    # At 0700 every day
    cron: 0 0 7 * * *
  shedlock-lock-at-most-for: PT2M

errorreport:
  creation-error-mail-template:
    subject: Fel vid skapande av fakturafiler - %s (%s)
    html-prefix: >
      <!DOCTYPE html>
      <html lang="en" xmlns="http://www.w3.org/1999/xhtml"><body>
    body-prefix: > 
        <b>Följande problem har inträffat vid generering av fakturafiler (%s)</b>
        <p>
    list-prefix: <i>%s fel:</i><ul>
    list-item: <li>%s</li>
    list-suffix: </ul>
    body-suffix: >
        Exekveringens request-id är %s
        </p>
        <p>
          <b>Med vänlig hälsning <br/>
          <a href="mailto:%s">%s</a></b>
        </p>
    html-suffix: </body></html>
  transfer-error-mail-template:
    subject: Fel vid överföring av fakturafiler - %s (%s)
    html-prefix: >
      <!DOCTYPE html>
      <html lang="en" xmlns="http://www.w3.org/1999/xhtml"><body>
    body-prefix: > 
        <b>Följande problem har inträffat vid överföring av fakturafiler (%s)</b>
        <p>
    list-prefix: <ul>
    list-item: <li>%s</li>
    list-suffix: </ul>
    body-suffix: >
        Exekveringens request-id är %s
        </p>
        <p>
          <b>Med vänlig hälsning <br/>
          <a href="mailto:%s">%s</a></b>
        </p>
    html-suffix: </body></html>
  recipients:
  sender: teamunmasked@sundsvall.se